name = "gtk-4-fortran"
description = "With this file gtk-fortran can be used as a fpm dependency. But if you want a full build and install of gtk-fortran on your system, you must use CMake."
version = "4.2.0"
license = "GPL-3.0-or-later"
author = "Vincent Magnin et al."
maintainer = "https://github.com/vmagnin/gtk-fortran/issues"
copyright = "2011-2022 Vincent Magnin et al."
homepage = "https://github.com/vmagnin/gtk-fortran/wiki"
keywords = ["gtk-fortran", "GUI", "GTK", "fpm"]

# When gtk-fortran is used as a fpm dependency, fpm will automatically discover
# the gtk-fortran modules in the gtk-fortran/src/ directory.

